"
" Custom local config for github.com/tlhunter/vimrc
"

set confirm
set guifont=Inconsolata:h14
set tabstop=4
set expandtab
set shiftwidth=4
set noswapfile
set nowrap

" The Silver Searcher
if executable('ag')
    " Use ag over grep
    set grepprg=ag\ --nogroup\ --nocolor
    " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

    " ag is fast enough that CtrlP doesn't need to cache
    let g:ctrlp_use_caching = 0
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" auto find with NERDTreeFind
autocmd BufEnter * if &modifiable | NERDTreeFind | wincmd p | endif
